# Generated by Django 5.1.4 on 2025-02-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
