# Generated by Django 5.1.4 on 2025-02-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepolicy',
            name='type',
            field=models.CharField(choices=[('TL', 'Term Life'), ('HL', 'Health'), ('VH', 'Vehicle')], default='TL', max_length=2),
        ),
    ]
